import { MigrationInterface, QueryRunner } from "typeorm";

export class AddUserApprovalColumns1753576068525 implements MigrationInterface {
    name = 'AddUserApprovalColumns1753576068525'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`usuarios\` DROP FOREIGN KEY \`usuarios_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`perfiles_medicos\` DROP FOREIGN KEY \`perfiles_medicos_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`pacientes\` DROP FOREIGN KEY \`pacientes_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`citas\` DROP FOREIGN KEY \`citas_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`citas\` DROP FOREIGN KEY \`citas_ibfk_2\``);
        await queryRunner.query(`ALTER TABLE \`citas\` DROP FOREIGN KEY \`citas_ibfk_3\``);
        await queryRunner.query(`ALTER TABLE \`historias_clinicas\` DROP FOREIGN KEY \`historias_clinicas_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`historias_clinicas\` DROP FOREIGN KEY \`historias_clinicas_ibfk_2\``);
        await queryRunner.query(`ALTER TABLE \`historias_clinicas\` DROP FOREIGN KEY \`historias_clinicas_ibfk_3\``);
        await queryRunner.query(`DROP INDEX \`email\` ON \`usuarios\``);
        await queryRunner.query(`DROP INDEX \`rol_id\` ON \`usuarios\``);
        await queryRunner.query(`DROP INDEX \`usuario_id\` ON \`perfiles_medicos\``);
        await queryRunner.query(`DROP INDEX \`numero_registro_medico\` ON \`perfiles_medicos\``);
        await queryRunner.query(`DROP INDEX \`usuario_id\` ON \`pacientes\``);
        await queryRunner.query(`DROP INDEX \`numero_identificacion\` ON \`pacientes\``);
        await queryRunner.query(`DROP INDEX \`paciente_id\` ON \`citas\``);
        await queryRunner.query(`DROP INDEX \`doctor_id\` ON \`citas\``);
        await queryRunner.query(`DROP INDEX \`aprobada_por\` ON \`citas\``);
        await queryRunner.query(`DROP INDEX \`paciente_id\` ON \`historias_clinicas\``);
        await queryRunner.query(`DROP INDEX \`doctor_id\` ON \`historias_clinicas\``);
        await queryRunner.query(`DROP INDEX \`cita_id\` ON \`historias_clinicas\``);
        await queryRunner.query(`ALTER TABLE \`usuarios\` ADD \`is_approved\` tinyint NOT NULL DEFAULT 1`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` ADD \`approval_status\` varchar(255) NOT NULL DEFAULT 'approved'`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` ADD \`approved_by\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` ADD \`approval_date\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` ADD \`rejection_reason\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`roles\` DROP COLUMN \`nombre\``);
        await queryRunner.query(`ALTER TABLE \`roles\` ADD \`nombre\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`roles\` CHANGE \`activo\` \`activo\` tinyint NOT NULL DEFAULT 1`);
        await queryRunner.query(`ALTER TABLE \`roles\` CHANGE \`fecha_creacion\` \`fecha_creacion\` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` ADD UNIQUE INDEX \`IDX_446adfc18b35418aac32ae0b7b\` (\`email\`)`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` DROP COLUMN \`nombre\``);
        await queryRunner.query(`ALTER TABLE \`usuarios\` ADD \`nombre\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` DROP COLUMN \`apellido\``);
        await queryRunner.query(`ALTER TABLE \`usuarios\` ADD \`apellido\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` DROP COLUMN \`telefono\``);
        await queryRunner.query(`ALTER TABLE \`usuarios\` ADD \`telefono\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` DROP COLUMN \`direccion\``);
        await queryRunner.query(`ALTER TABLE \`usuarios\` ADD \`direccion\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` CHANGE \`fecha_creacion\` \`fecha_creacion\` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` CHANGE \`is_verified\` \`is_verified\` tinyint NOT NULL DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` CHANGE \`verification_code\` \`verification_code\` varchar(10) NULL`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` CHANGE \`reset_password_token\` \`reset_password_token\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` CHANGE \`reset_password_expires\` \`reset_password_expires\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`perfiles_medicos\` ADD UNIQUE INDEX \`IDX_71295a1059bbb912f3270b3fa9\` (\`usuario_id\`)`);
        await queryRunner.query(`ALTER TABLE \`perfiles_medicos\` DROP COLUMN \`numero_registro_medico\``);
        await queryRunner.query(`ALTER TABLE \`perfiles_medicos\` ADD \`numero_registro_medico\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`perfiles_medicos\` ADD UNIQUE INDEX \`IDX_6a6e9f2cb6cd21e0e6d1a040b3\` (\`numero_registro_medico\`)`);
        await queryRunner.query(`ALTER TABLE \`perfiles_medicos\` DROP COLUMN \`especialidad\``);
        await queryRunner.query(`ALTER TABLE \`perfiles_medicos\` ADD \`especialidad\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`perfiles_medicos\` CHANGE \`subespecialidades\` \`subespecialidades\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`perfiles_medicos\` DROP COLUMN \`universidad_egreso\``);
        await queryRunner.query(`ALTER TABLE \`perfiles_medicos\` ADD \`universidad_egreso\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`perfiles_medicos\` CHANGE \`biografia\` \`biografia\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`perfiles_medicos\` CHANGE \`acepta_nuevos_pacientes\` \`acepta_nuevos_pacientes\` tinyint NOT NULL DEFAULT 1`);
        await queryRunner.query(`ALTER TABLE \`perfiles_medicos\` CHANGE \`tarifa_consulta\` \`tarifa_consulta\` decimal(10,2) NULL`);
        await queryRunner.query(`ALTER TABLE \`perfiles_medicos\` DROP COLUMN \`telefono_consultorio\``);
        await queryRunner.query(`ALTER TABLE \`perfiles_medicos\` ADD \`telefono_consultorio\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`perfiles_medicos\` DROP COLUMN \`direccion_consultorio\``);
        await queryRunner.query(`ALTER TABLE \`perfiles_medicos\` ADD \`direccion_consultorio\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`perfiles_medicos\` DROP COLUMN \`ciudad\``);
        await queryRunner.query(`ALTER TABLE \`perfiles_medicos\` ADD \`ciudad\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`perfiles_medicos\` CHANGE \`dias_atencion\` \`dias_atencion\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`perfiles_medicos\` CHANGE \`hora_inicio\` \`hora_inicio\` time NULL`);
        await queryRunner.query(`ALTER TABLE \`perfiles_medicos\` CHANGE \`hora_fin\` \`hora_fin\` time NULL`);
        await queryRunner.query(`ALTER TABLE \`perfiles_medicos\` CHANGE \`hora_almuerzo_inicio\` \`hora_almuerzo_inicio\` time NULL`);
        await queryRunner.query(`ALTER TABLE \`perfiles_medicos\` CHANGE \`hora_almuerzo_fin\` \`hora_almuerzo_fin\` time NULL`);
        await queryRunner.query(`ALTER TABLE \`perfiles_medicos\` CHANGE \`activo\` \`activo\` tinyint NOT NULL DEFAULT 1`);
        await queryRunner.query(`ALTER TABLE \`perfiles_medicos\` CHANGE \`verificado_colegio\` \`verificado_colegio\` tinyint NOT NULL DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE \`perfiles_medicos\` CHANGE \`fecha_verificacion\` \`fecha_verificacion\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`perfiles_medicos\` CHANGE \`fecha_creacion\` \`fecha_creacion\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`perfiles_medicos\` CHANGE \`fecha_actualizacion\` \`fecha_actualizacion\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`pacientes\` ADD UNIQUE INDEX \`IDX_3065e2172ba8e5572489cceac7\` (\`usuario_id\`)`);
        await queryRunner.query(`ALTER TABLE \`pacientes\` DROP COLUMN \`numero_identificacion\``);
        await queryRunner.query(`ALTER TABLE \`pacientes\` ADD \`numero_identificacion\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`pacientes\` ADD UNIQUE INDEX \`IDX_c88fbb0066cd8b74ddb1d8e7f4\` (\`numero_identificacion\`)`);
        await queryRunner.query(`ALTER TABLE \`pacientes\` DROP COLUMN \`estado_civil\``);
        await queryRunner.query(`ALTER TABLE \`pacientes\` ADD \`estado_civil\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`pacientes\` DROP COLUMN \`ocupacion\``);
        await queryRunner.query(`ALTER TABLE \`pacientes\` ADD \`ocupacion\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`pacientes\` DROP COLUMN \`ciudad_residencia\``);
        await queryRunner.query(`ALTER TABLE \`pacientes\` ADD \`ciudad_residencia\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`pacientes\` DROP COLUMN \`barrio\``);
        await queryRunner.query(`ALTER TABLE \`pacientes\` ADD \`barrio\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`pacientes\` DROP COLUMN \`eps\``);
        await queryRunner.query(`ALTER TABLE \`pacientes\` ADD \`eps\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`pacientes\` DROP COLUMN \`numero_afiliacion\``);
        await queryRunner.query(`ALTER TABLE \`pacientes\` ADD \`numero_afiliacion\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`pacientes\` DROP COLUMN \`tipo_afiliacion\``);
        await queryRunner.query(`ALTER TABLE \`pacientes\` ADD \`tipo_afiliacion\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`pacientes\` DROP COLUMN \`contacto_emergencia_nombre\``);
        await queryRunner.query(`ALTER TABLE \`pacientes\` ADD \`contacto_emergencia_nombre\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`pacientes\` DROP COLUMN \`contacto_emergencia_telefono\``);
        await queryRunner.query(`ALTER TABLE \`pacientes\` ADD \`contacto_emergencia_telefono\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`pacientes\` DROP COLUMN \`contacto_emergencia_parentesco\``);
        await queryRunner.query(`ALTER TABLE \`pacientes\` ADD \`contacto_emergencia_parentesco\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`pacientes\` CHANGE \`antecedentesMedicos\` \`antecedentesMedicos\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`pacientes\` CHANGE \`antecedentesQuirurgicos\` \`antecedentesQuirurgicos\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`pacientes\` CHANGE \`antecedentesFamiliares\` \`antecedentesFamiliares\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`pacientes\` CHANGE \`alergias\` \`alergias\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`pacientes\` CHANGE \`medicamentosActuales\` \`medicamentosActuales\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`pacientes\` CHANGE \`peso\` \`peso\` decimal(5,2) NULL`);
        await queryRunner.query(`ALTER TABLE \`pacientes\` CHANGE \`estatura\` \`estatura\` decimal(5,2) NULL`);
        await queryRunner.query(`ALTER TABLE \`pacientes\` DROP COLUMN \`grupo_sanguineo\``);
        await queryRunner.query(`ALTER TABLE \`pacientes\` ADD \`grupo_sanguineo\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`pacientes\` CHANGE \`acepta_comunicaciones\` \`acepta_comunicaciones\` tinyint NOT NULL DEFAULT 1`);
        await queryRunner.query(`ALTER TABLE \`pacientes\` CHANGE \`prefiere_whatsapp\` \`prefiere_whatsapp\` tinyint NOT NULL DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE \`pacientes\` CHANGE \`prefiere_email\` \`prefiere_email\` tinyint NOT NULL DEFAULT 1`);
        await queryRunner.query(`ALTER TABLE \`pacientes\` CHANGE \`prefiere_sms\` \`prefiere_sms\` tinyint NOT NULL DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE \`pacientes\` CHANGE \`activo\` \`activo\` tinyint NOT NULL DEFAULT 1`);
        await queryRunner.query(`ALTER TABLE \`pacientes\` CHANGE \`primera_consulta\` \`primera_consulta\` tinyint NOT NULL DEFAULT 1`);
        await queryRunner.query(`ALTER TABLE \`pacientes\` CHANGE \`fecha_registro\` \`fecha_registro\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`pacientes\` CHANGE \`fecha_actualizacion\` \`fecha_actualizacion\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`citas\` CHANGE \`motivoConsulta\` \`motivoConsulta\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`citas\` CHANGE \`notasDoctor\` \`notasDoctor\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`citas\` CHANGE \`notasPaciente\` \`notasPaciente\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`citas\` CHANGE \`costo\` \`costo\` decimal(10,2) NULL`);
        await queryRunner.query(`ALTER TABLE \`citas\` CHANGE \`fecha_creacion\` \`fecha_creacion\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`citas\` CHANGE \`fecha_actualizacion\` \`fecha_actualizacion\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`citas\` CHANGE \`aprobada_por\` \`aprobada_por\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`citas\` CHANGE \`fecha_aprobacion\` \`fecha_aprobacion\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`citas\` CHANGE \`razonRechazo\` \`razonRechazo\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`citas\` CHANGE \`recordatorio_enviado\` \`recordatorio_enviado\` tinyint NOT NULL DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE \`historias_clinicas\` CHANGE \`cita_id\` \`cita_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`historias_clinicas\` CHANGE \`antecedentesMedicos\` \`antecedentesMedicos\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`historias_clinicas\` CHANGE \`antecedentesQuirurgicos\` \`antecedentesQuirurgicos\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`historias_clinicas\` CHANGE \`alergias\` \`alergias\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`historias_clinicas\` CHANGE \`medicamentosActuales\` \`medicamentosActuales\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`historias_clinicas\` CHANGE \`signosVitales\` \`signosVitales\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`historias_clinicas\` CHANGE \`diagnosticoDiferencial\` \`diagnosticoDiferencial\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`historias_clinicas\` CHANGE \`examenesSolicitados\` \`examenesSolicitados\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`historias_clinicas\` CHANGE \`interconsultas\` \`interconsultas\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`historias_clinicas\` CHANGE \`recomendaciones\` \`recomendaciones\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`historias_clinicas\` CHANGE \`observaciones\` \`observaciones\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`historias_clinicas\` CHANGE \`proximaConsulta\` \`proximaConsulta\` date NULL`);
        await queryRunner.query(`ALTER TABLE \`historias_clinicas\` CHANGE \`fecha_consulta\` \`fecha_consulta\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`historias_clinicas\` CHANGE \`fecha_actualizacion\` \`fecha_actualizacion\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`REL_71295a1059bbb912f3270b3fa9\` ON \`perfiles_medicos\` (\`usuario_id\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`REL_3065e2172ba8e5572489cceac7\` ON \`pacientes\` (\`usuario_id\`)`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` ADD CONSTRAINT \`FK_9e519760a660751f4fa21453d3e\` FOREIGN KEY (\`rol_id\`) REFERENCES \`roles\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`perfiles_medicos\` ADD CONSTRAINT \`FK_71295a1059bbb912f3270b3fa9a\` FOREIGN KEY (\`usuario_id\`) REFERENCES \`usuarios\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`pacientes\` ADD CONSTRAINT \`FK_3065e2172ba8e5572489cceac74\` FOREIGN KEY (\`usuario_id\`) REFERENCES \`usuarios\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`citas\` ADD CONSTRAINT \`FK_cb9ae070f79985c5df13ac6bb3a\` FOREIGN KEY (\`paciente_id\`) REFERENCES \`usuarios\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`citas\` ADD CONSTRAINT \`FK_2a98f2543d190bfff5723ed0356\` FOREIGN KEY (\`doctor_id\`) REFERENCES \`usuarios\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`citas\` ADD CONSTRAINT \`FK_396fd59bc81634d49631e1d218b\` FOREIGN KEY (\`aprobada_por\`) REFERENCES \`usuarios\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`historias_clinicas\` ADD CONSTRAINT \`FK_7681732d1c66a675e9fb8d5586d\` FOREIGN KEY (\`paciente_id\`) REFERENCES \`usuarios\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`historias_clinicas\` ADD CONSTRAINT \`FK_d8bd744f5835fb5b15488e61882\` FOREIGN KEY (\`doctor_id\`) REFERENCES \`usuarios\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`historias_clinicas\` ADD CONSTRAINT \`FK_08494003fdddd5e0336bfbf8054\` FOREIGN KEY (\`cita_id\`) REFERENCES \`citas\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`historias_clinicas\` DROP FOREIGN KEY \`FK_08494003fdddd5e0336bfbf8054\``);
        await queryRunner.query(`ALTER TABLE \`historias_clinicas\` DROP FOREIGN KEY \`FK_d8bd744f5835fb5b15488e61882\``);
        await queryRunner.query(`ALTER TABLE \`historias_clinicas\` DROP FOREIGN KEY \`FK_7681732d1c66a675e9fb8d5586d\``);
        await queryRunner.query(`ALTER TABLE \`citas\` DROP FOREIGN KEY \`FK_396fd59bc81634d49631e1d218b\``);
        await queryRunner.query(`ALTER TABLE \`citas\` DROP FOREIGN KEY \`FK_2a98f2543d190bfff5723ed0356\``);
        await queryRunner.query(`ALTER TABLE \`citas\` DROP FOREIGN KEY \`FK_cb9ae070f79985c5df13ac6bb3a\``);
        await queryRunner.query(`ALTER TABLE \`pacientes\` DROP FOREIGN KEY \`FK_3065e2172ba8e5572489cceac74\``);
        await queryRunner.query(`ALTER TABLE \`perfiles_medicos\` DROP FOREIGN KEY \`FK_71295a1059bbb912f3270b3fa9a\``);
        await queryRunner.query(`ALTER TABLE \`usuarios\` DROP FOREIGN KEY \`FK_9e519760a660751f4fa21453d3e\``);
        await queryRunner.query(`DROP INDEX \`REL_3065e2172ba8e5572489cceac7\` ON \`pacientes\``);
        await queryRunner.query(`DROP INDEX \`REL_71295a1059bbb912f3270b3fa9\` ON \`perfiles_medicos\``);
        await queryRunner.query(`ALTER TABLE \`historias_clinicas\` CHANGE \`fecha_actualizacion\` \`fecha_actualizacion\` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`historias_clinicas\` CHANGE \`fecha_consulta\` \`fecha_consulta\` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`historias_clinicas\` CHANGE \`proximaConsulta\` \`proximaConsulta\` date NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`historias_clinicas\` CHANGE \`observaciones\` \`observaciones\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`historias_clinicas\` CHANGE \`recomendaciones\` \`recomendaciones\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`historias_clinicas\` CHANGE \`interconsultas\` \`interconsultas\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`historias_clinicas\` CHANGE \`examenesSolicitados\` \`examenesSolicitados\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`historias_clinicas\` CHANGE \`diagnosticoDiferencial\` \`diagnosticoDiferencial\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`historias_clinicas\` CHANGE \`signosVitales\` \`signosVitales\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`historias_clinicas\` CHANGE \`medicamentosActuales\` \`medicamentosActuales\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`historias_clinicas\` CHANGE \`alergias\` \`alergias\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`historias_clinicas\` CHANGE \`antecedentesQuirurgicos\` \`antecedentesQuirurgicos\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`historias_clinicas\` CHANGE \`antecedentesMedicos\` \`antecedentesMedicos\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`historias_clinicas\` CHANGE \`cita_id\` \`cita_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`citas\` CHANGE \`recordatorio_enviado\` \`recordatorio_enviado\` tinyint(1) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`citas\` CHANGE \`razonRechazo\` \`razonRechazo\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`citas\` CHANGE \`fecha_aprobacion\` \`fecha_aprobacion\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`citas\` CHANGE \`aprobada_por\` \`aprobada_por\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`citas\` CHANGE \`fecha_actualizacion\` \`fecha_actualizacion\` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`citas\` CHANGE \`fecha_creacion\` \`fecha_creacion\` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`citas\` CHANGE \`costo\` \`costo\` decimal(10,2) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`citas\` CHANGE \`notasPaciente\` \`notasPaciente\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`citas\` CHANGE \`notasDoctor\` \`notasDoctor\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`citas\` CHANGE \`motivoConsulta\` \`motivoConsulta\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`pacientes\` CHANGE \`fecha_actualizacion\` \`fecha_actualizacion\` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`pacientes\` CHANGE \`fecha_registro\` \`fecha_registro\` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`pacientes\` CHANGE \`primera_consulta\` \`primera_consulta\` tinyint(1) NOT NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`pacientes\` CHANGE \`activo\` \`activo\` tinyint(1) NOT NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`pacientes\` CHANGE \`prefiere_sms\` \`prefiere_sms\` tinyint(1) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`pacientes\` CHANGE \`prefiere_email\` \`prefiere_email\` tinyint(1) NOT NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`pacientes\` CHANGE \`prefiere_whatsapp\` \`prefiere_whatsapp\` tinyint(1) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`pacientes\` CHANGE \`acepta_comunicaciones\` \`acepta_comunicaciones\` tinyint(1) NOT NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`pacientes\` DROP COLUMN \`grupo_sanguineo\``);
        await queryRunner.query(`ALTER TABLE \`pacientes\` ADD \`grupo_sanguineo\` varchar(5) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`pacientes\` CHANGE \`estatura\` \`estatura\` decimal(5,2) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`pacientes\` CHANGE \`peso\` \`peso\` decimal(5,2) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`pacientes\` CHANGE \`medicamentosActuales\` \`medicamentosActuales\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`pacientes\` CHANGE \`alergias\` \`alergias\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`pacientes\` CHANGE \`antecedentesFamiliares\` \`antecedentesFamiliares\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`pacientes\` CHANGE \`antecedentesQuirurgicos\` \`antecedentesQuirurgicos\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`pacientes\` CHANGE \`antecedentesMedicos\` \`antecedentesMedicos\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`pacientes\` DROP COLUMN \`contacto_emergencia_parentesco\``);
        await queryRunner.query(`ALTER TABLE \`pacientes\` ADD \`contacto_emergencia_parentesco\` varchar(50) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`pacientes\` DROP COLUMN \`contacto_emergencia_telefono\``);
        await queryRunner.query(`ALTER TABLE \`pacientes\` ADD \`contacto_emergencia_telefono\` varchar(20) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`pacientes\` DROP COLUMN \`contacto_emergencia_nombre\``);
        await queryRunner.query(`ALTER TABLE \`pacientes\` ADD \`contacto_emergencia_nombre\` varchar(100) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`pacientes\` DROP COLUMN \`tipo_afiliacion\``);
        await queryRunner.query(`ALTER TABLE \`pacientes\` ADD \`tipo_afiliacion\` varchar(20) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`pacientes\` DROP COLUMN \`numero_afiliacion\``);
        await queryRunner.query(`ALTER TABLE \`pacientes\` ADD \`numero_afiliacion\` varchar(50) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`pacientes\` DROP COLUMN \`eps\``);
        await queryRunner.query(`ALTER TABLE \`pacientes\` ADD \`eps\` varchar(100) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`pacientes\` DROP COLUMN \`barrio\``);
        await queryRunner.query(`ALTER TABLE \`pacientes\` ADD \`barrio\` varchar(100) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`pacientes\` DROP COLUMN \`ciudad_residencia\``);
        await queryRunner.query(`ALTER TABLE \`pacientes\` ADD \`ciudad_residencia\` varchar(100) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`pacientes\` DROP COLUMN \`ocupacion\``);
        await queryRunner.query(`ALTER TABLE \`pacientes\` ADD \`ocupacion\` varchar(100) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`pacientes\` DROP COLUMN \`estado_civil\``);
        await queryRunner.query(`ALTER TABLE \`pacientes\` ADD \`estado_civil\` varchar(20) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`pacientes\` DROP INDEX \`IDX_c88fbb0066cd8b74ddb1d8e7f4\``);
        await queryRunner.query(`ALTER TABLE \`pacientes\` DROP COLUMN \`numero_identificacion\``);
        await queryRunner.query(`ALTER TABLE \`pacientes\` ADD \`numero_identificacion\` varchar(20) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`pacientes\` DROP INDEX \`IDX_3065e2172ba8e5572489cceac7\``);
        await queryRunner.query(`ALTER TABLE \`perfiles_medicos\` CHANGE \`fecha_actualizacion\` \`fecha_actualizacion\` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`perfiles_medicos\` CHANGE \`fecha_creacion\` \`fecha_creacion\` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`perfiles_medicos\` CHANGE \`fecha_verificacion\` \`fecha_verificacion\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`perfiles_medicos\` CHANGE \`verificado_colegio\` \`verificado_colegio\` tinyint(1) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`perfiles_medicos\` CHANGE \`activo\` \`activo\` tinyint(1) NOT NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`perfiles_medicos\` CHANGE \`hora_almuerzo_fin\` \`hora_almuerzo_fin\` time NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`perfiles_medicos\` CHANGE \`hora_almuerzo_inicio\` \`hora_almuerzo_inicio\` time NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`perfiles_medicos\` CHANGE \`hora_fin\` \`hora_fin\` time NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`perfiles_medicos\` CHANGE \`hora_inicio\` \`hora_inicio\` time NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`perfiles_medicos\` CHANGE \`dias_atencion\` \`dias_atencion\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`perfiles_medicos\` DROP COLUMN \`ciudad\``);
        await queryRunner.query(`ALTER TABLE \`perfiles_medicos\` ADD \`ciudad\` varchar(100) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`perfiles_medicos\` DROP COLUMN \`direccion_consultorio\``);
        await queryRunner.query(`ALTER TABLE \`perfiles_medicos\` ADD \`direccion_consultorio\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`perfiles_medicos\` DROP COLUMN \`telefono_consultorio\``);
        await queryRunner.query(`ALTER TABLE \`perfiles_medicos\` ADD \`telefono_consultorio\` varchar(20) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`perfiles_medicos\` CHANGE \`tarifa_consulta\` \`tarifa_consulta\` decimal(10,2) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`perfiles_medicos\` CHANGE \`acepta_nuevos_pacientes\` \`acepta_nuevos_pacientes\` tinyint(1) NOT NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`perfiles_medicos\` CHANGE \`biografia\` \`biografia\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`perfiles_medicos\` DROP COLUMN \`universidad_egreso\``);
        await queryRunner.query(`ALTER TABLE \`perfiles_medicos\` ADD \`universidad_egreso\` varchar(200) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`perfiles_medicos\` CHANGE \`subespecialidades\` \`subespecialidades\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`perfiles_medicos\` DROP COLUMN \`especialidad\``);
        await queryRunner.query(`ALTER TABLE \`perfiles_medicos\` ADD \`especialidad\` varchar(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`perfiles_medicos\` DROP INDEX \`IDX_6a6e9f2cb6cd21e0e6d1a040b3\``);
        await queryRunner.query(`ALTER TABLE \`perfiles_medicos\` DROP COLUMN \`numero_registro_medico\``);
        await queryRunner.query(`ALTER TABLE \`perfiles_medicos\` ADD \`numero_registro_medico\` varchar(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`perfiles_medicos\` DROP INDEX \`IDX_71295a1059bbb912f3270b3fa9\``);
        await queryRunner.query(`ALTER TABLE \`usuarios\` CHANGE \`reset_password_expires\` \`reset_password_expires\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` CHANGE \`reset_password_token\` \`reset_password_token\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` CHANGE \`verification_code\` \`verification_code\` varchar(10) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` CHANGE \`is_verified\` \`is_verified\` tinyint(1) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` CHANGE \`fecha_creacion\` \`fecha_creacion\` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` DROP COLUMN \`direccion\``);
        await queryRunner.query(`ALTER TABLE \`usuarios\` ADD \`direccion\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` DROP COLUMN \`telefono\``);
        await queryRunner.query(`ALTER TABLE \`usuarios\` ADD \`telefono\` varchar(20) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` DROP COLUMN \`apellido\``);
        await queryRunner.query(`ALTER TABLE \`usuarios\` ADD \`apellido\` varchar(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` DROP COLUMN \`nombre\``);
        await queryRunner.query(`ALTER TABLE \`usuarios\` ADD \`nombre\` varchar(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` DROP INDEX \`IDX_446adfc18b35418aac32ae0b7b\``);
        await queryRunner.query(`ALTER TABLE \`roles\` CHANGE \`fecha_creacion\` \`fecha_creacion\` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`roles\` CHANGE \`activo\` \`activo\` tinyint(1) NOT NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`roles\` DROP COLUMN \`nombre\``);
        await queryRunner.query(`ALTER TABLE \`roles\` ADD \`nombre\` varchar(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` DROP COLUMN \`rejection_reason\``);
        await queryRunner.query(`ALTER TABLE \`usuarios\` DROP COLUMN \`approval_date\``);
        await queryRunner.query(`ALTER TABLE \`usuarios\` DROP COLUMN \`approved_by\``);
        await queryRunner.query(`ALTER TABLE \`usuarios\` DROP COLUMN \`approval_status\``);
        await queryRunner.query(`ALTER TABLE \`usuarios\` DROP COLUMN \`is_approved\``);
        await queryRunner.query(`CREATE INDEX \`cita_id\` ON \`historias_clinicas\` (\`cita_id\`)`);
        await queryRunner.query(`CREATE INDEX \`doctor_id\` ON \`historias_clinicas\` (\`doctor_id\`)`);
        await queryRunner.query(`CREATE INDEX \`paciente_id\` ON \`historias_clinicas\` (\`paciente_id\`)`);
        await queryRunner.query(`CREATE INDEX \`aprobada_por\` ON \`citas\` (\`aprobada_por\`)`);
        await queryRunner.query(`CREATE INDEX \`doctor_id\` ON \`citas\` (\`doctor_id\`)`);
        await queryRunner.query(`CREATE INDEX \`paciente_id\` ON \`citas\` (\`paciente_id\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`numero_identificacion\` ON \`pacientes\` (\`numero_identificacion\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`usuario_id\` ON \`pacientes\` (\`usuario_id\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`numero_registro_medico\` ON \`perfiles_medicos\` (\`numero_registro_medico\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`usuario_id\` ON \`perfiles_medicos\` (\`usuario_id\`)`);
        await queryRunner.query(`CREATE INDEX \`rol_id\` ON \`usuarios\` (\`rol_id\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`email\` ON \`usuarios\` (\`email\`)`);
        await queryRunner.query(`ALTER TABLE \`historias_clinicas\` ADD CONSTRAINT \`historias_clinicas_ibfk_3\` FOREIGN KEY (\`cita_id\`) REFERENCES \`citas\`(\`id\`) ON DELETE RESTRICT ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`historias_clinicas\` ADD CONSTRAINT \`historias_clinicas_ibfk_2\` FOREIGN KEY (\`doctor_id\`) REFERENCES \`usuarios\`(\`id\`) ON DELETE RESTRICT ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`historias_clinicas\` ADD CONSTRAINT \`historias_clinicas_ibfk_1\` FOREIGN KEY (\`paciente_id\`) REFERENCES \`usuarios\`(\`id\`) ON DELETE RESTRICT ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`citas\` ADD CONSTRAINT \`citas_ibfk_3\` FOREIGN KEY (\`aprobada_por\`) REFERENCES \`usuarios\`(\`id\`) ON DELETE RESTRICT ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`citas\` ADD CONSTRAINT \`citas_ibfk_2\` FOREIGN KEY (\`doctor_id\`) REFERENCES \`usuarios\`(\`id\`) ON DELETE RESTRICT ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`citas\` ADD CONSTRAINT \`citas_ibfk_1\` FOREIGN KEY (\`paciente_id\`) REFERENCES \`usuarios\`(\`id\`) ON DELETE RESTRICT ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`pacientes\` ADD CONSTRAINT \`pacientes_ibfk_1\` FOREIGN KEY (\`usuario_id\`) REFERENCES \`usuarios\`(\`id\`) ON DELETE RESTRICT ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`perfiles_medicos\` ADD CONSTRAINT \`perfiles_medicos_ibfk_1\` FOREIGN KEY (\`usuario_id\`) REFERENCES \`usuarios\`(\`id\`) ON DELETE RESTRICT ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` ADD CONSTRAINT \`usuarios_ibfk_1\` FOREIGN KEY (\`rol_id\`) REFERENCES \`roles\`(\`id\`) ON DELETE RESTRICT ON UPDATE RESTRICT`);
    }

}
