import { MigrationInterface, QueryRunner } from "typeorm";

export class MakeUniversityFieldsOptional1757892798108 implements MigrationInterface {
    name = 'MakeUniversityFieldsOptional1757892798108'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`product_reservations\` DROP FOREIGN KEY \`fk_reservation_confirmed_by\``);
        await queryRunner.query(`ALTER TABLE \`product_reservations\` DROP FOREIGN KEY \`fk_reservation_patient\``);
        await queryRunner.query(`ALTER TABLE \`product_reservations\` DROP FOREIGN KEY \`fk_reservation_product\``);
        await queryRunner.query(`ALTER TABLE \`patient_documents\` DROP FOREIGN KEY \`patient_documents_ibfk_1\``);
        await queryRunner.query(`DROP INDEX \`idx_patient_status\` ON \`product_reservations\``);
        await queryRunner.query(`DROP INDEX \`idx_product_status\` ON \`product_reservations\``);
        await queryRunner.query(`DROP INDEX \`IDX_patient_documents_patient_id\` ON \`patient_documents\``);
        await queryRunner.query(`ALTER TABLE \`roles\` CHANGE \`fecha_creacion\` \`fecha_creacion\` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`perfiles_medicos\` CHANGE \`subespecialidades\` \`subespecialidades\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`perfiles_medicos\` CHANGE \`universidad_egreso\` \`universidad_egreso\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`perfiles_medicos\` CHANGE \`año_graduacion\` \`año_graduacion\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`perfiles_medicos\` CHANGE \`biografia\` \`biografia\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`perfiles_medicos\` CHANGE \`tarifa_consulta\` \`tarifa_consulta\` decimal(10,2) NULL`);
        await queryRunner.query(`ALTER TABLE \`perfiles_medicos\` CHANGE \`telefono_consultorio\` \`telefono_consultorio\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`perfiles_medicos\` CHANGE \`direccion_consultorio\` \`direccion_consultorio\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`perfiles_medicos\` CHANGE \`ciudad\` \`ciudad\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`perfiles_medicos\` CHANGE \`dias_atencion\` \`dias_atencion\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`perfiles_medicos\` CHANGE \`hora_inicio\` \`hora_inicio\` time NULL`);
        await queryRunner.query(`ALTER TABLE \`perfiles_medicos\` CHANGE \`hora_fin\` \`hora_fin\` time NULL`);
        await queryRunner.query(`ALTER TABLE \`perfiles_medicos\` CHANGE \`hora_almuerzo_inicio\` \`hora_almuerzo_inicio\` time NULL`);
        await queryRunner.query(`ALTER TABLE \`perfiles_medicos\` CHANGE \`hora_almuerzo_fin\` \`hora_almuerzo_fin\` time NULL`);
        await queryRunner.query(`ALTER TABLE \`perfiles_medicos\` CHANGE \`fecha_verificacion\` \`fecha_verificacion\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`pacientes\` CHANGE \`numero_identificacion\` \`numero_identificacion\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`pacientes\` CHANGE \`fecha_nacimiento\` \`fecha_nacimiento\` date NULL`);
        await queryRunner.query(`ALTER TABLE \`pacientes\` CHANGE \`eps\` \`eps\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`pacientes\` CHANGE \`numero_afiliacion\` \`numero_afiliacion\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`pacientes\` CHANGE \`tipo_afiliacion\` \`tipo_afiliacion\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`pacientes\` CHANGE \`contacto_emergencia_nombre\` \`contacto_emergencia_nombre\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`pacientes\` CHANGE \`contacto_emergencia_telefono\` \`contacto_emergencia_telefono\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`pacientes\` CHANGE \`contacto_emergencia_parentesco\` \`contacto_emergencia_parentesco\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` CHANGE \`telefono\` \`telefono\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` CHANGE \`direccion\` \`direccion\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` CHANGE \`fecha_creacion\` \`fecha_creacion\` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` CHANGE \`verification_code\` \`verification_code\` varchar(10) NULL`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` CHANGE \`reset_password_token\` \`reset_password_token\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` CHANGE \`reset_password_expires\` \`reset_password_expires\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` CHANGE \`password_reset_code\` \`password_reset_code\` varchar(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` CHANGE \`password_reset_code_expires\` \`password_reset_code_expires\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` CHANGE \`approved_by\` \`approved_by\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` CHANGE \`approval_date\` \`approval_date\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` CHANGE \`rejection_reason\` \`rejection_reason\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`product_reservations\` CHANGE \`quantity\` \`quantity\` int NOT NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`product_reservations\` CHANGE \`status\` \`status\` enum ('pending', 'confirmed', 'delivered', 'cancelled') NOT NULL DEFAULT 'pending'`);
        await queryRunner.query(`ALTER TABLE \`product_reservations\` CHANGE \`notes\` \`notes\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`product_reservations\` CHANGE \`doctor_notes\` \`doctor_notes\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`product_reservations\` CHANGE \`confirmed_by_doctor_id\` \`confirmed_by_doctor_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`product_reservations\` CHANGE \`confirmed_at\` \`confirmed_at\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`product_reservations\` CHANGE \`delivered_at\` \`delivered_at\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`product_reservations\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`product_reservations\` ADD \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`product_reservations\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`product_reservations\` ADD \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`description\` \`description\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`stock\` \`stock\` int NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`image_url\` \`image_url\` varchar(500) NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`category\` \`category\` varchar(100) NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`brand\` \`brand\` varchar(100) NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`is_available\` \`is_available\` tinyint NOT NULL DEFAULT 1`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`requires_prescription\` \`requires_prescription\` tinyint NOT NULL DEFAULT 1`);
        await queryRunner.query(`ALTER TABLE \`products\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`products\` ADD \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`products\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`products\` ADD \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`patient_documents\` DROP COLUMN \`file_path\``);
        await queryRunner.query(`ALTER TABLE \`patient_documents\` ADD \`file_path\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`patient_documents\` DROP COLUMN \`mime_type\``);
        await queryRunner.query(`ALTER TABLE \`patient_documents\` ADD \`mime_type\` varchar(255) NOT NULL DEFAULT 'application/pdf'`);
        await queryRunner.query(`ALTER TABLE \`patient_documents\` DROP COLUMN \`description\``);
        await queryRunner.query(`ALTER TABLE \`patient_documents\` ADD \`description\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`patient_documents\` DROP COLUMN \`upload_date\``);
        await queryRunner.query(`ALTER TABLE \`patient_documents\` ADD \`upload_date\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`citas\` CHANGE \`motivoConsulta\` \`motivoConsulta\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`citas\` CHANGE \`notasDoctor\` \`notasDoctor\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`citas\` CHANGE \`notasPaciente\` \`notasPaciente\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`citas\` CHANGE \`costo\` \`costo\` decimal(10,2) NULL`);
        await queryRunner.query(`ALTER TABLE \`citas\` CHANGE \`aprobada_por\` \`aprobada_por\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`citas\` CHANGE \`fecha_aprobacion\` \`fecha_aprobacion\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`citas\` CHANGE \`razonRechazo\` \`razonRechazo\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`notificaciones\` CHANGE \`cita_id\` \`cita_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`notificaciones\` CHANGE \`doctor_nombre\` \`doctor_nombre\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`notificaciones\` CHANGE \`fecha_cita\` \`fecha_cita\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`historias_clinicas\` DROP FOREIGN KEY \`FK_08494003fdddd5e0336bfbf8054\``);
        await queryRunner.query(`ALTER TABLE \`historias_clinicas\` CHANGE \`cita_id\` \`cita_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`historias_clinicas\` CHANGE \`antecedentesMedicos\` \`antecedentesMedicos\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`historias_clinicas\` CHANGE \`antecedentesQuirurgicos\` \`antecedentesQuirurgicos\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`historias_clinicas\` CHANGE \`alergias\` \`alergias\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`historias_clinicas\` CHANGE \`medicamentosActuales\` \`medicamentosActuales\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`historias_clinicas\` CHANGE \`signosVitales\` \`signosVitales\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`historias_clinicas\` CHANGE \`diagnosticoDiferencial\` \`diagnosticoDiferencial\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`historias_clinicas\` CHANGE \`examenesSolicitados\` \`examenesSolicitados\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`historias_clinicas\` CHANGE \`interconsultas\` \`interconsultas\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`historias_clinicas\` CHANGE \`recomendaciones\` \`recomendaciones\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`historias_clinicas\` CHANGE \`observaciones\` \`observaciones\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`historias_clinicas\` CHANGE \`proximaConsulta\` \`proximaConsulta\` date NULL`);
        await queryRunner.query(`DROP INDEX \`IDX_204f1e1c389704b1aa394be97d\` ON \`flexible_doctor_schedules\``);
        await queryRunner.query(`ALTER TABLE \`flexible_doctor_schedules\` CHANGE \`start_date\` \`start_date\` date NULL`);
        await queryRunner.query(`ALTER TABLE \`flexible_doctor_schedules\` CHANGE \`end_date\` \`end_date\` date NULL`);
        await queryRunner.query(`ALTER TABLE \`flexible_doctor_schedules\` CHANGE \`day_of_week\` \`day_of_week\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`flexible_doctor_schedules\` CHANGE \`day_of_month\` \`day_of_month\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`flexible_doctor_schedules\` DROP COLUMN \`time_slots\``);
        await queryRunner.query(`ALTER TABLE \`flexible_doctor_schedules\` ADD \`time_slots\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`flexible_doctor_schedules\` CHANGE \`notes\` \`notes\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`flexible_doctor_schedules\` CHANGE \`reason\` \`reason\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`doctor_schedules\` CHANGE \`start_time\` \`start_time\` time NULL`);
        await queryRunner.query(`ALTER TABLE \`doctor_schedules\` CHANGE \`end_time\` \`end_time\` time NULL`);
        await queryRunner.query(`ALTER TABLE \`doctor_schedules\` CHANGE \`break_start\` \`break_start\` time NULL`);
        await queryRunner.query(`ALTER TABLE \`doctor_schedules\` CHANGE \`break_end\` \`break_end\` time NULL`);
        await queryRunner.query(`ALTER TABLE \`doctor_schedules\` DROP COLUMN \`custom_slots\``);
        await queryRunner.query(`ALTER TABLE \`doctor_schedules\` ADD \`custom_slots\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`doctor_schedules\` CHANGE \`notes\` \`notes\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`doctor_schedules\` CHANGE \`recurring_day\` \`recurring_day\` int NULL`);
        await queryRunner.query(`CREATE INDEX \`IDX_85466f20fcb49c2fa8d9d68058\` ON \`flexible_doctor_schedules\` (\`doctor_id\`, \`start_date\`, \`end_date\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_204f1e1c389704b1aa394be97d\` ON \`flexible_doctor_schedules\` (\`doctor_id\`, \`day_of_week\`, \`schedule_type\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_8c3d7d6fe7c27b130faee0b02f\` ON \`flexible_doctor_schedules\` (\`doctor_id\`, \`schedule_type\`, \`start_date\`)`);
        await queryRunner.query(`ALTER TABLE \`product_reservations\` ADD CONSTRAINT \`FK_0303803272459f9abfe77e8720e\` FOREIGN KEY (\`product_id\`) REFERENCES \`products\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`product_reservations\` ADD CONSTRAINT \`FK_1e63d3d80e916d1b3b2f7c06461\` FOREIGN KEY (\`patient_id\`) REFERENCES \`usuarios\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`product_reservations\` ADD CONSTRAINT \`FK_c5b4fab4c8a8d6118c74bee034f\` FOREIGN KEY (\`confirmed_by_doctor_id\`) REFERENCES \`usuarios\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`patient_documents\` ADD CONSTRAINT \`FK_1a2f2efebe9442fc0c64c5d8db3\` FOREIGN KEY (\`patient_id\`) REFERENCES \`pacientes\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`citas\` ADD CONSTRAINT \`FK_396fd59bc81634d49631e1d218b\` FOREIGN KEY (\`aprobada_por\`) REFERENCES \`usuarios\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`notificaciones\` ADD CONSTRAINT \`FK_f9d65ba4deb2c1d44c8fad299fd\` FOREIGN KEY (\`cita_id\`) REFERENCES \`citas\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`historias_clinicas\` ADD CONSTRAINT \`FK_08494003fdddd5e0336bfbf8054\` FOREIGN KEY (\`cita_id\`) REFERENCES \`citas\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`historias_clinicas\` DROP FOREIGN KEY \`FK_08494003fdddd5e0336bfbf8054\``);
        await queryRunner.query(`ALTER TABLE \`notificaciones\` DROP FOREIGN KEY \`FK_f9d65ba4deb2c1d44c8fad299fd\``);
        await queryRunner.query(`ALTER TABLE \`citas\` DROP FOREIGN KEY \`FK_396fd59bc81634d49631e1d218b\``);
        await queryRunner.query(`ALTER TABLE \`patient_documents\` DROP FOREIGN KEY \`FK_1a2f2efebe9442fc0c64c5d8db3\``);
        await queryRunner.query(`ALTER TABLE \`product_reservations\` DROP FOREIGN KEY \`FK_c5b4fab4c8a8d6118c74bee034f\``);
        await queryRunner.query(`ALTER TABLE \`product_reservations\` DROP FOREIGN KEY \`FK_1e63d3d80e916d1b3b2f7c06461\``);
        await queryRunner.query(`ALTER TABLE \`product_reservations\` DROP FOREIGN KEY \`FK_0303803272459f9abfe77e8720e\``);
        await queryRunner.query(`DROP INDEX \`IDX_8c3d7d6fe7c27b130faee0b02f\` ON \`flexible_doctor_schedules\``);
        await queryRunner.query(`DROP INDEX \`IDX_204f1e1c389704b1aa394be97d\` ON \`flexible_doctor_schedules\``);
        await queryRunner.query(`DROP INDEX \`IDX_85466f20fcb49c2fa8d9d68058\` ON \`flexible_doctor_schedules\``);
        await queryRunner.query(`ALTER TABLE \`doctor_schedules\` CHANGE \`recurring_day\` \`recurring_day\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`doctor_schedules\` CHANGE \`notes\` \`notes\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`doctor_schedules\` DROP COLUMN \`custom_slots\``);
        await queryRunner.query(`ALTER TABLE \`doctor_schedules\` ADD \`custom_slots\` longtext COLLATE "utf8mb4_bin" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`doctor_schedules\` CHANGE \`break_end\` \`break_end\` time NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`doctor_schedules\` CHANGE \`break_start\` \`break_start\` time NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`doctor_schedules\` CHANGE \`end_time\` \`end_time\` time NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`doctor_schedules\` CHANGE \`start_time\` \`start_time\` time NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`flexible_doctor_schedules\` CHANGE \`reason\` \`reason\` varchar(255) COLLATE "utf8mb4_general_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`flexible_doctor_schedules\` CHANGE \`notes\` \`notes\` text COLLATE "utf8mb4_general_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`flexible_doctor_schedules\` DROP COLUMN \`time_slots\``);
        await queryRunner.query(`ALTER TABLE \`flexible_doctor_schedules\` ADD \`time_slots\` longtext COLLATE "utf8mb4_bin" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`flexible_doctor_schedules\` CHANGE \`day_of_month\` \`day_of_month\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`flexible_doctor_schedules\` CHANGE \`day_of_week\` \`day_of_week\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`flexible_doctor_schedules\` CHANGE \`end_date\` \`end_date\` date NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`flexible_doctor_schedules\` CHANGE \`start_date\` \`start_date\` date NULL DEFAULT 'NULL'`);
        await queryRunner.query(`CREATE INDEX \`IDX_204f1e1c389704b1aa394be97d\` ON \`flexible_doctor_schedules\` (\`doctor_id\`, \`day_of_week\`, \`schedule_type\`)`);
        await queryRunner.query(`ALTER TABLE \`historias_clinicas\` CHANGE \`proximaConsulta\` \`proximaConsulta\` date NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`historias_clinicas\` CHANGE \`observaciones\` \`observaciones\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`historias_clinicas\` CHANGE \`recomendaciones\` \`recomendaciones\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`historias_clinicas\` CHANGE \`interconsultas\` \`interconsultas\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`historias_clinicas\` CHANGE \`examenesSolicitados\` \`examenesSolicitados\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`historias_clinicas\` CHANGE \`diagnosticoDiferencial\` \`diagnosticoDiferencial\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`historias_clinicas\` CHANGE \`signosVitales\` \`signosVitales\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`historias_clinicas\` CHANGE \`medicamentosActuales\` \`medicamentosActuales\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`historias_clinicas\` CHANGE \`alergias\` \`alergias\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`historias_clinicas\` CHANGE \`antecedentesQuirurgicos\` \`antecedentesQuirurgicos\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`historias_clinicas\` CHANGE \`antecedentesMedicos\` \`antecedentesMedicos\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`historias_clinicas\` CHANGE \`cita_id\` \`cita_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`historias_clinicas\` ADD CONSTRAINT \`FK_08494003fdddd5e0336bfbf8054\` FOREIGN KEY (\`cita_id\`) REFERENCES \`citas\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`notificaciones\` CHANGE \`fecha_cita\` \`fecha_cita\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`notificaciones\` CHANGE \`doctor_nombre\` \`doctor_nombre\` varchar(255) COLLATE "utf8mb4_general_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`notificaciones\` CHANGE \`cita_id\` \`cita_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`citas\` CHANGE \`razonRechazo\` \`razonRechazo\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`citas\` CHANGE \`fecha_aprobacion\` \`fecha_aprobacion\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`citas\` CHANGE \`aprobada_por\` \`aprobada_por\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`citas\` CHANGE \`costo\` \`costo\` decimal(10,2) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`citas\` CHANGE \`notasPaciente\` \`notasPaciente\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`citas\` CHANGE \`notasDoctor\` \`notasDoctor\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`citas\` CHANGE \`motivoConsulta\` \`motivoConsulta\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`patient_documents\` DROP COLUMN \`upload_date\``);
        await queryRunner.query(`ALTER TABLE \`patient_documents\` ADD \`upload_date\` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`patient_documents\` DROP COLUMN \`description\``);
        await queryRunner.query(`ALTER TABLE \`patient_documents\` ADD \`description\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`patient_documents\` DROP COLUMN \`mime_type\``);
        await queryRunner.query(`ALTER TABLE \`patient_documents\` ADD \`mime_type\` varchar(100) NOT NULL DEFAULT ''application/pdf''`);
        await queryRunner.query(`ALTER TABLE \`patient_documents\` DROP COLUMN \`file_path\``);
        await queryRunner.query(`ALTER TABLE \`patient_documents\` ADD \`file_path\` varchar(500) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`products\` ADD \`updated_at\` timestamp(0) NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`products\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`products\` ADD \`created_at\` timestamp(0) NULL DEFAULT CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`requires_prescription\` \`requires_prescription\` tinyint(1) NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`is_available\` \`is_available\` tinyint(1) NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`brand\` \`brand\` varchar(100) COLLATE "utf8mb4_general_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`category\` \`category\` varchar(100) COLLATE "utf8mb4_general_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`image_url\` \`image_url\` varchar(500) COLLATE "utf8mb4_general_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`stock\` \`stock\` int NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`description\` \`description\` text COLLATE "utf8mb4_general_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`product_reservations\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`product_reservations\` ADD \`updated_at\` timestamp(0) NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`product_reservations\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`product_reservations\` ADD \`created_at\` timestamp(0) NULL DEFAULT CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`product_reservations\` CHANGE \`delivered_at\` \`delivered_at\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`product_reservations\` CHANGE \`confirmed_at\` \`confirmed_at\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`product_reservations\` CHANGE \`confirmed_by_doctor_id\` \`confirmed_by_doctor_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`product_reservations\` CHANGE \`doctor_notes\` \`doctor_notes\` text COLLATE "utf8mb4_general_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`product_reservations\` CHANGE \`notes\` \`notes\` text COLLATE "utf8mb4_general_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`product_reservations\` CHANGE \`status\` \`status\` enum COLLATE "utf8mb4_general_ci" ('pending', 'confirmed', 'delivered', 'cancelled') NULL DEFAULT ''pending''`);
        await queryRunner.query(`ALTER TABLE \`product_reservations\` CHANGE \`quantity\` \`quantity\` int NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` CHANGE \`rejection_reason\` \`rejection_reason\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` CHANGE \`approval_date\` \`approval_date\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` CHANGE \`approved_by\` \`approved_by\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` CHANGE \`password_reset_code_expires\` \`password_reset_code_expires\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` CHANGE \`password_reset_code\` \`password_reset_code\` varchar(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` CHANGE \`reset_password_expires\` \`reset_password_expires\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` CHANGE \`reset_password_token\` \`reset_password_token\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` CHANGE \`verification_code\` \`verification_code\` varchar(10) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` CHANGE \`fecha_creacion\` \`fecha_creacion\` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` CHANGE \`direccion\` \`direccion\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` CHANGE \`telefono\` \`telefono\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`pacientes\` CHANGE \`contacto_emergencia_parentesco\` \`contacto_emergencia_parentesco\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`pacientes\` CHANGE \`contacto_emergencia_telefono\` \`contacto_emergencia_telefono\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`pacientes\` CHANGE \`contacto_emergencia_nombre\` \`contacto_emergencia_nombre\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`pacientes\` CHANGE \`tipo_afiliacion\` \`tipo_afiliacion\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`pacientes\` CHANGE \`numero_afiliacion\` \`numero_afiliacion\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`pacientes\` CHANGE \`eps\` \`eps\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`pacientes\` CHANGE \`fecha_nacimiento\` \`fecha_nacimiento\` date NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`pacientes\` CHANGE \`numero_identificacion\` \`numero_identificacion\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`perfiles_medicos\` CHANGE \`fecha_verificacion\` \`fecha_verificacion\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`perfiles_medicos\` CHANGE \`hora_almuerzo_fin\` \`hora_almuerzo_fin\` time NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`perfiles_medicos\` CHANGE \`hora_almuerzo_inicio\` \`hora_almuerzo_inicio\` time NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`perfiles_medicos\` CHANGE \`hora_fin\` \`hora_fin\` time NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`perfiles_medicos\` CHANGE \`hora_inicio\` \`hora_inicio\` time NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`perfiles_medicos\` CHANGE \`dias_atencion\` \`dias_atencion\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`perfiles_medicos\` CHANGE \`ciudad\` \`ciudad\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`perfiles_medicos\` CHANGE \`direccion_consultorio\` \`direccion_consultorio\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`perfiles_medicos\` CHANGE \`telefono_consultorio\` \`telefono_consultorio\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`perfiles_medicos\` CHANGE \`tarifa_consulta\` \`tarifa_consulta\` decimal(10,2) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`perfiles_medicos\` CHANGE \`biografia\` \`biografia\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`perfiles_medicos\` CHANGE \`año_graduacion\` \`año_graduacion\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`perfiles_medicos\` CHANGE \`universidad_egreso\` \`universidad_egreso\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`perfiles_medicos\` CHANGE \`subespecialidades\` \`subespecialidades\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`roles\` CHANGE \`fecha_creacion\` \`fecha_creacion\` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP()`);
        await queryRunner.query(`CREATE INDEX \`IDX_patient_documents_patient_id\` ON \`patient_documents\` (\`patient_id\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_product_status\` ON \`product_reservations\` (\`product_id\`, \`status\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_patient_status\` ON \`product_reservations\` (\`patient_id\`, \`status\`)`);
        await queryRunner.query(`ALTER TABLE \`patient_documents\` ADD CONSTRAINT \`patient_documents_ibfk_1\` FOREIGN KEY (\`patient_id\`) REFERENCES \`pacientes\`(\`id\`) ON DELETE CASCADE ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`product_reservations\` ADD CONSTRAINT \`fk_reservation_product\` FOREIGN KEY (\`product_id\`) REFERENCES \`products\`(\`id\`) ON DELETE CASCADE ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`product_reservations\` ADD CONSTRAINT \`fk_reservation_patient\` FOREIGN KEY (\`patient_id\`) REFERENCES \`usuarios\`(\`id\`) ON DELETE CASCADE ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`product_reservations\` ADD CONSTRAINT \`fk_reservation_confirmed_by\` FOREIGN KEY (\`confirmed_by_doctor_id\`) REFERENCES \`usuarios\`(\`id\`) ON DELETE SET NULL ON UPDATE RESTRICT`);
    }

}
